# Database PostgreSQL configuration

[database]

connection_string = "host=localhost port=5432 user=postgres password=admin dbname=test_gorm sslmode=disable"
max_idle_connections = 5
max_open_connections = 20
connection_max_lifetime = "60s"

###############################################################################

# HTTP server configuration

[http]

server_address = ":8000"

###############################################################################
