# Database PostgreSQL configuration

[database]

connection_string = "host=your_postgres_host port=your_port user=your_db_user password=your_db_password dbname=your_db_name sslmode=your_sslmode_disable_or_enable"
max_idle_connections = 5 # your_max_idle_connections
max_open_connections = 20 # your_max_open_connections
connection_max_lifetime = "60s" # your_connection_max_lifetime

###############################################################################

# HTTP server configuration

[http]

server_address = ":8000" # your_server_address

###############################################################################
